<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="27123" started-at="2018-05-01T08:41:27Z" finished-at="2018-05-01T08:41:55Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="27123" started-at="2018-05-01T08:41:27Z" finished-at="2018-05-01T08:41:55Z">
      <class name="Log4jTest.Log4jTesting">
        <test-method status="PASS" signature="initialization()[pri:0, instance:Log4jTest.Log4jTesting@d8355a8]" name="initialization" is-config="true" duration-ms="13558" started-at="2018-05-01T14:11:27Z" finished-at="2018-05-01T14:11:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialization -->
        <test-method status="FAIL" signature="HomePageVerificationTest()[pri:1, instance:Log4jTest.Log4jTesting@d8355a8]" name="HomePageVerificationTest" duration-ms="2041" started-at="2018-05-01T14:11:41Z" finished-at="2018-05-01T14:11:43Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Free CRM in the cloud software boosts sales] but found [Free CRM software in the cloud powers sales and customer service]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Free CRM in the cloud software boosts sales] but found [Free CRM software in the cloud powers sales and customer service]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at Log4jTest.Log4jTesting.HomePageVerificationTest(Log4jTesting.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- HomePageVerificationTest -->
        <test-method status="PASS" signature="Teardown()[pri:0, instance:Log4jTest.Log4jTesting@d8355a8]" name="Teardown" is-config="true" duration-ms="677" started-at="2018-05-01T14:11:43Z" finished-at="2018-05-01T14:11:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Teardown -->
        <test-method status="PASS" signature="initialization()[pri:0, instance:Log4jTest.Log4jTesting@d8355a8]" name="initialization" is-config="true" duration-ms="10113" started-at="2018-05-01T14:11:44Z" finished-at="2018-05-01T14:11:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialization -->
        <test-method status="PASS" signature="VerifyLogoTest()[pri:2, instance:Log4jTest.Log4jTesting@d8355a8]" name="VerifyLogoTest" duration-ms="83" started-at="2018-05-01T14:11:54Z" finished-at="2018-05-01T14:11:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyLogoTest -->
        <test-method status="PASS" signature="Teardown()[pri:0, instance:Log4jTest.Log4jTesting@d8355a8]" name="Teardown" is-config="true" duration-ms="605" started-at="2018-05-01T14:11:54Z" finished-at="2018-05-01T14:11:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Teardown -->
      </class> <!-- Log4jTest.Log4jTesting -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
